server:
  servlet:
    context-path: /zhengfang
    # 端口号
  port: 18080

#数据源
spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      druid:
        initial-size: 1
        max-active: 200
        min-idle: 1
        max-wait: 60000
      datasource:
        master:
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://192.168.1.16:1433;DatabaseName=NG0001;encrypt=true;trustServerCertificate=true
          username: sa
          password: newbd@505!zf
        one:
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://192.168.1.16:1433;DatabaseName=NG0001;encrypt=true;trustServerCertificate=true
          username: sa
          password: newbd@505!zf

  #swagger3.0 兼容问题
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER

#i8相关
i8:
  currenturl: http://www.zfkg.com:18080
  #外网ip地址或域名
  url: http://www.zfkg.com:2222
  #内网ip地址
  ip: http://www.zfkg.com:2222
  #接口专用账号
  user: 9006
  #接口专用账号密码
  pwd:
  #数据库账套号 （注意用双引号，0开头会被识别为数值，省略）
  database: "0001"
  #数据库连接串（用于请求i8提供的内部webservice）
  #    dblink: ConnectType=SqlClient;Server=172.21.205.168,1433;Database=NG0002;User Id=Sa;Password=Zjzx123?
  dblink: ConnectType=ORACLEClient;Data Source=192.168.0.227:1521/ORACLE;UserId=NG0001;Password=zjsj123
  #单点登录串
  ssoUrl: http://localhost
  ocode:
  databaseName: "NG0001"
  appurl: http://appserver.netcall.cc/EnterpriseInfoService/wechat/pages/seeyon.html?platform=h5&NGCorpId=760002

#http 请求相关
http:
  maxTotal: 800
  defaultMaxPerRoute: 80
  connectTimeout: 60000
  connectionRequestTimeout: 300000
  socketTimeout: 120000

#定时任务schedule （corn表达式从左到右（用空格隔开）：秒 分 小时 月份 星期中的日期 年份）
#例子 0 0/5 * * * ?    每隔 5 分钟运行
corn: 0 0/5 * * * ?




oa:
  url:
  registerCode:
  username:
  password:
i6p:
  url:
  esn:

bip:
  url: https://bip.zfkg.com
